CREATE TABLE exercises (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_teacher INT NOT NULL,
    post_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL
);